# Numpy and Writing Efficient Python

In [48]:
import numpy
numpy.__version__

'2.5.3'

In [28]:
# Importing Libraries
import numpy as np

In [30]:
# In Python
a = 80
b = 70
addition = a+b
print(addition)

150


In [31]:
# A List in Python

In [32]:
nums = [2, 90, 5, 9, 70, 2, 99]

In [33]:
# Python code to multiply each number in the num list by 2
nums * 2

# This proves that in python we can't perform broadcasting (calculations etc.)

[2, 90, 5, 9, 70, 2, 99, 2, 90, 5, 9, 70, 2, 99]

In [34]:
for num in nums:
    num * 2
    print(nums)

[2, 90, 5, 9, 70, 2, 99]
[2, 90, 5, 9, 70, 2, 99]
[2, 90, 5, 9, 70, 2, 99]
[2, 90, 5, 9, 70, 2, 99]
[2, 90, 5, 9, 70, 2, 99]
[2, 90, 5, 9, 70, 2, 99]
[2, 90, 5, 9, 70, 2, 99]


In [35]:
squared_nums = []
for num in nums:
    squared_nums.append(num / 2)

print(squared_nums)

# We've used 4 to 5 lines of code to perform a simple calculation.
# With numpy it's easier

[1.0, 45.0, 2.5, 4.5, 35.0, 1.0, 49.5]


**BroadCasting in Numpy**

In [36]:
radius = np.array([2, 4, 60, 8, 9, 3])

diameter = radius * 2

print(diameter)

[  4   8 120  16  18   6]


**BMI Calculation Illustration**

In [37]:
weight = [45, 60, 70, 65, 67, 70, 40]

In [38]:
# Lists do not support Boolean Indexing but Arrays do
# weight > 50

In [39]:
height = [130, 160, 170, 200, 210, 140, 159]

In [40]:
# Doing this in python gives us a Type error uncomment below to see the error
# weight / height ** 2
# uncomment it to see the error

**Numpy Solution**

In [41]:
np_weight = np.array(weight)

In [42]:
np_height = np.array(height)

In [43]:
bmi = np_weight / np_height ** 2
print(bmi)

[0.00266272 0.00234375 0.00242215 0.001625   0.00151927 0.00357143
 0.00158222]


**Bolean Indexing**

In [44]:
bmi > 0.0020

array([ True,  True,  True, False, False,  True, False])

In [45]:
type(bmi)

numpy.ndarray

In [46]:
bmi

array([0.00266272, 0.00234375, 0.00242215, 0.001625  , 0.00151927,
       0.00357143, 0.00158222])

**Creating a 2D Array**

- To make it easy tounderstand view this as two 1D Arrays stack on each other

In [ ]:
                #   0      1     2    3      4
np_2d = np.array([[1.75, 1.68, 1.71, 1.89, 1.79],  # 0
                  [65.4, 59.0, 60.9, 70.5, 45.9]]) # 1
np_2d

array([[ 1.75,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.  , 60.9 , 70.5 , 45.9 ]])

In [56]:
np_2d.shape

(2, 5)

**Subsetting or indexing in numpy arrays**

In [58]:
np_2d[0]

array([1.75, 1.68, 1.71, 1.89, 1.79])

In [63]:
np_2d[0, 2]

np.float64(1.71)

In [64]:
np_2d[0][2]

np.float64(1.71)

In [ ]:
np_2d[1,:]

# 1 means the row
# : means the column - ':' in python means print all the way to end of that column

array([65.4, 59. , 60.9, 70.5, 45.9])

In [ ]:
np_2d[:, 1:3]

# firstly, the ':' tells it to return both rows
# then for both rows return the entries in the 1st and 2nd index because the 3rd one is excluded

array([[ 1.68,  1.71],
       [59.  , 60.9 ]])